
development:
  adapter: mysql2
  encoding: utf8
  database: tipdem_dev
  pool: 5
  username: root
  password: root
  host: localhost

test: &test
  adapter: mysql2
  encoding: utf8
  database: tipdem_test
  pool: 5
  username: root
  password: root
  host: localhost

stage:
  adapter: mysql2
  encoding: utf8
  database: stage_livechains
  pool: 5
  username: stage_root
  password: gauchogaucho
  host: localhost
  reconnect: true

production:
  adapter: mysql2
  encoding: utf8
  database: tipdem
  username: tipdem_root
  password: gauch0gauch0
  host: localhost
  pool: 5
  reconnect: true

